const projectData = [
  {
    id: 'shreedevi-engineers',
    title: 'Shreedevi Engineers Industrial Website (Live)',
    image: '/assets/sridevi.png',
    themeColor: 'blue',
    shortDescription: 'Official online presence for a real-world surface grinding company. Includes product listings, dynamic forms, certificate uploads, and client interaction modules.',
    fullDescription: 'Developed an official online presence for a real-world surface grinding company. The website features product listings, dynamic form submissions, certificate uploads, and client interaction modules. Built with React, Node.js, Express, and MongoDB, styled with Tailwind CSS.',
    role: 'Full Stack Developer',
    timeline: 'Jan 2024 – Mar 2024',
    client: 'Shreedevi Engineers',
    problem: 'The client needed a modern, responsive website to showcase their products and enable online client interaction, replacing their outdated static site.',
    solution: 'Designed and built a full-featured web app with product listings, dynamic forms, and certificate uploads. Used a modern tech stack for scalability and maintainability.',
    challenges: 'Integrating legacy data, ensuring mobile responsiveness, and optimizing for fast load times.',
    results: 'Increased client leads by 30% and improved user engagement. The site now supports dynamic client interactions and document uploads.',
    team: 'Solo project',
    features: [
      'Product listing with categories',
      'Client-side and server-side form validations',
      'Upload and render government certificates (Udyam, GST)',
      'Order placement module with authentication',
      'Admin panel for managing entries',
      'MongoDB schema design and indexing',
      'Modern UI using Tailwind CSS',
      '100% responsive and cross-browser compatible',
    ],
    tech: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    gallery: ['/assets/sridevi1.png', '/assets/sridevi2.png', '/assets/sridevi3.png', '/assets/sridevi4.png'],
    github: 'https://github.com/MayureshMankar/fischer-cutter',
    demo: 'https://www.srideviengineers.com/',
  },
  {
    id: 'ai-assistant',
    title: 'AI Coding Assistant Pro v2.0 (Live)',
    image: '/assets/ai-assistant.png',
    themeColor: 'blue',
    shortDescription: 'Professional VS Code-like IDE with free AI models, fixed chat display, and auto language detection. Available as web app, VS Code extension, and desktop application.',
    fullDescription: 'AI Coding Assistant Pro is a comprehensive AI-powered development tool that transforms into a professional VS Code-like IDE. It features 8 free AI models from OpenRouter, fixed chat display issues, and auto language detection. Available in three formats: web application, VS Code extension, and desktop application.',
    role: 'Full Stack Developer',
    timeline: 'Jul 2024 – Aug 2024',
    client: 'Personal Project',
    problem: 'Needed a professional AI coding assistant with free models, proper chat display, and seamless integration with development environments.',
    solution: 'Built a multi-platform AI assistant with VS Code-like interface, 8 free AI models, professional shortcuts, file management, and context awareness. Supports auto language detection for 15+ programming languages.',
    challenges: 'Integrating multiple platforms (web, VS Code extension, desktop), managing free AI models, ensuring context awareness, and maintaining conversation history.',
    results: 'Successfully deployed all three platforms with working free models. Fixed all chat display issues and implemented auto language detection. Users can now access the assistant through their preferred development environment.',
    team: 'Solo project',
    features: [
      'VS Code-like Interface: Activity bar, explorer, editor, status bar',
      'Desktop App: Standalone Electron application with auto-updates',
      '8 Free AI Models: DeepSeek V3, Qwen3 variants, Gemini 2.0 Flash',
      'Professional Shortcuts: Ctrl+Shift+A (chat), Ctrl+Shift+E (explain), etc.',
      'File Management: Upload, open, and manage code files',
      'Context Awareness: AI knows your open files and conversation history',
      'Auto Language Detection: Supports 15+ programming languages',
    ],
    tech: ['React', 'TypeScript', 'Node.js', 'Python', 'Flask', 'Electron', 'VS Code API', 'OpenRouter API', 'Tailwind CSS'],
    gallery: ['/assets/ai-assistant.png', '/assets/ai-assistant2.png'],
    github: 'https://github.com/MayureshMankar/AI-Assistant',
    demo: 'https://ai-assistant-navy-nu.vercel.app/',
  },
   {
    id: 'ai-voice-assistant',
    title: 'AI Voice Assistant (Live)',
    image: '/assets/ai-voice-assistant.png',
    themeColor: 'blue',
    shortDescription: 'A full-stack AI-powered voice assistant that uses OpenAI and speech recognition to interact with users through natural language.',
    fullDescription: 'AI Voice Assistant is a full-stack application that enables users to interact with an AI assistant using voice commands. It utilizes OpenAI for generating intelligent responses and leverages modern frontend and backend technologies for a smooth, real-time conversational experience. The assistant can listen, process, and respond to users using speech synthesis.',
    role: 'Full Stack Developer',
    timeline: 'Aug 2024 – Aug 2024',
    client: 'Personal Project',
    problem: 'Wanted to create a conversational AI that understands and responds to natural voice inputs in real time.',
    solution: 'Built a client-server application integrating Web Speech API for voice recognition and text-to-speech, OpenAI for intelligence, and modern tools like Vite and TypeScript for performance.',
    challenges: 'Synchronizing real-time audio input/output with AI responses and managing cross-browser speech API inconsistencies.',
    results: 'Successfully deployed a working demo with real-time voice-based interaction. Positive feedback for usability and responsiveness.',
    team: 'Solo project',
    features: [
      'Real-time voice recognition',
      'AI-powered responses using OpenAI',
      'Speech synthesis output',
      'Fast frontend using Vite',
      'Full-stack integration and deployment',
      'Minimal and clean UI',
      'Optimized for performance and speed'  
    ],
    tech: ['TypeScript', 'Vite', 'Node.js', 'Express', 'OpenAI API', 'Web Speech API', 'Render'],
    gallery: ['/assets/ai-voice-assistant.png', '/assets/ai-voice-assistant2.png', '/assets/ai-voice-assistant3.jpg', '/assets/ai-voice-assistant4.png'],
    github: 'https://github.com/MayureshMankar/AI-Voice-Assistant',
    demo: 'https://ai-voice-assistant-vjkc.onrender.com/',
  },
  {
    id: 'noteshub',
    title: 'NotesHub - Student Notes Portal (Live)',
    image: '/assets/noteshub.png',
    themeColor: 'purple',
    shortDescription: 'A premium web application that allows students to upload, share, and access study notes. Built with Next.js, React, and MongoDB.',
    fullDescription: 'NotesHub is a premium student notes portal that enables students to upload study materials and share them with others. The platform features secure file uploads, password protection for private notes, and a responsive design that works across all devices. Built with modern web technologies for optimal performance and search engine visibility.',
    role: 'Full Stack Developer',
    timeline: '2024',
    client: 'Personal Project',
    problem: 'Students often struggle to find quality study materials and lack a centralized platform to share resources with peers.',
    solution: 'Developed a comprehensive notes sharing platform with upload, search, and download capabilities. Implemented both public and password-protected note sharing options.',
    challenges: 'Implementing secure file handling, creating an intuitive UI/UX for students, and ensuring responsive design across all devices.',
    results: 'Created a fully functional platform where students can easily share and access study materials. The platform supports multiple file formats and includes SEO optimization for better discoverability.',
    team: 'Solo project',
    features: [
      'Student note upload with titles, descriptions, subjects, and tags',
      'Search functionality by title, description, subject, or tags',
      'Password protection for private notes',
      'Public access to shared notes',
      'Responsive design for desktop, tablet, and mobile',
      'SEO optimization with Next.js',
      'File validation for common document formats',
      '10MB file size limit for uploads'
    ],
    tech: ['Next.js', 'React', 'TypeScript', 'MongoDB', 'Mongoose', 'Tailwind CSS'],
    gallery: ['/assets/noteshub1.png', '/assets/noteshub2.png', '/assets/noteshub3.png', '/assets/noteshub4.png'],
    github: 'https://github.com/MayureshMankar/student-notes-portal',
    demo: 'https://student-notes-portal.vercel.app/',
  },
  {
    id: 'ai-lead-finder',
    title: 'AI Lead Finder',
    image: '/assets/ai-lead-finder.png',
    themeColor: 'green',
    shortDescription: 'A powerful SaaS application that automates job scraping and outreach to help you find your next opportunity. Features LinkedIn integration, AI-powered email generation, and lead management.',
    fullDescription: 'AI Lead Finder is a comprehensive SaaS application that automates job scraping and outreach to help users find their next career opportunity. It features LinkedIn integration with Selenium automation, AI-powered personalized email generation using GPT, and centralized lead management dashboard.',
    role: 'Full Stack Developer',
    timeline: '2024',
    client: 'Personal Project',
    problem: 'Job seekers need an automated solution to find and reach out to potential employers without manually searching and crafting personalized messages.',
    solution: 'Developed a full-stack SaaS application with job scraping capabilities, AI-powered message generation, and lead tracking. Users can scrape jobs from multiple sources, generate personalized outreach messages, and manage their leads in one place.',
    challenges: 'Implementing reliable web scraping that bypasses anti-bot measures, integrating AI for personalized messaging, ensuring email deliverability, and creating an intuitive user interface.',
    results: 'Created a fully functional SaaS application that helps job seekers automate their job search process. Users can scrape hundreds of jobs, generate personalized messages, and track their outreach efforts.',
    team: 'Solo project',
    features: [
      'Job Scraping: LinkedIn integration with Selenium automation',
      'Smart Filtering: Filter by keyword, location, and job type',
      'Batch Processing: Scrape multiple jobs at once with configurable limits',
      'AI-Powered Messages: Generate personalized outreach messages using GPT',
      'Email Extraction: Automatically extract contact emails from job descriptions',
      'Bulk Campaigns: Send outreach emails to multiple companies at once',
      'Centralized Dashboard: View all leads in one place',
      'User Authentication: JWT-based authentication system',
    ],
    tech: ['Python', 'Flask', 'SQLAlchemy', 'MySQL', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Selenium', 'OpenAI API', 'JWT'],
    gallery: ['/assets/ai-lead-finder1.png', '/assets/ai-lead-finder2.png', '/assets/ai-lead-finder3.png', '/assets/ai-lead-finder4.png'],
    github: 'https://github.com/MayureshMankar/ai-lead-finder',
  },
  {
    id: 'whispering-soul',
    title: 'Whispering Soul',
    image: '/assets/whisper.png',
    themeColor: 'pink',
    shortDescription: 'A modern website project aimed at expressing emotion and creativity through digital storytelling and immersive design. Currently under active development.',
    fullDescription: 'Whispering Soul is a modern website project focused on digital storytelling and immersive design. The project is currently under active development and aims to push the boundaries of creative web experiences.',
    role: 'UI/UX Designer & Frontend Developer',
    timeline: 'Apr 2024 – Present',
    client: 'Personal/Experimental',
    problem: 'Wanted to explore new ways of expressing emotion and narrative through web design and animation.',
    solution: 'Experimenting with advanced CSS, SVG, and animation techniques to create an immersive, interactive storytelling experience.',
    challenges: 'Pushing the limits of browser-based animation while maintaining performance and accessibility.',
    results: 'Project in progress. Early feedback highlights the unique design and emotional impact.',
    team: 'Solo project',
    features: [
      'Immersive digital storytelling',
      'Custom animations and transitions',
      'Experimental layout and typography',
      'Audio and mood-based theming',
      'Emotion-driven user experience',
    ],
    tech: ['React', 'Framer Motion', 'Tailwind', 'Custom SVG', 'UI/UX Design'],
    gallery: ['/assets/whisper1.png', '/assets/whisper2.png', '/assets/whisper3.png', '/assets/whisper4.png'],
    github: 'https://github.com/MayureshMankar/Whispering-Souls',
  },
  {
    id: 'portfolio-website',
    title: 'Photography Portfolio',
    image: '/assets/photography-portfolio.png',
    themeColor: 'purple',
    shortDescription: 'A modern photography portfolio website built with React, TypeScript, and Tailwind CSS, showcasing creative works with elegant design and smooth animations.',
    fullDescription: 'A modern photography portfolio website designed to showcase creative works with an elegant, minimalist design. Built with React, TypeScript, and Tailwind CSS, featuring smooth animations, responsive layout, and optimized performance. The website includes sections for portfolio gallery, services, testimonials, and contact information.',
    role: 'UI/UX Designer & Full Stack Developer',
    timeline: '2024',
    client: 'Personal Project',
    problem: 'Needed a professional platform to showcase photography work with a focus on visual impact and user experience.',
    solution: 'Designed and developed a visually stunning portfolio website with a focus on photography display, using modern web technologies and animation libraries for an engaging user experience.',
    challenges: 'Creating a design that puts photography first while maintaining performance and responsiveness across all devices.',
    results: 'A professional photography portfolio website that effectively showcases creative work with an elegant, minimalist design and smooth user experience.',
    team: 'Solo project',
    features: [
      'Modern, minimalist design focused on photography',
      'Responsive layout for all device sizes',
      'Smooth animations and transitions',
      'Gallery section with categorized portfolio items',
      'Services and pricing information',
      'Client testimonials section',
      'Contact form with business information',
      'Performance optimized with lazy loading',
    ],
    tech: ['React', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Wouter'],
    gallery: ['/assets/photoportfolio1.png', '/assets/photoportfolio2.png', '/assets/photoportfolio3.png', '/assets/photoportfolio4.png'],
    github: 'https://github.com/MayureshMankar/photographer-portfolio',
  },
  
  
];

export default projectData;